// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentaContenedores.Data;

#nullable disable

namespace RentaContenedores.Migrations
{
    [DbContext(typeof(ContenedoresDataContext))]
    partial class ContenedoresDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RentaContenedores.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Juan Perez",
                            Telefono = "55523412345"
                        });
                });

            modelBuilder.Entity("RentaContenedores.Models.Contenedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Adeudo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("adeudo");

                    b.Property<string>("Dimensiones")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dimensiones");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<string>("Pasillo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("pasillo");

                    b.Property<DateOnly>("UltimoPago")
                        .HasColumnType("date")
                        .HasColumnName("ultimo_pago");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("id_cliente");

                    b.ToTable("contenedor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adeudo = 0m,
                            Dimensiones = "3x6",
                            Numero = 1,
                            Pasillo = "A",
                            UltimoPago = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            Adeudo = 0m,
                            Dimensiones = "3x6",
                            Numero = 2,
                            Pasillo = "A",
                            UltimoPago = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            Adeudo = 0m,
                            Dimensiones = "3x3",
                            Numero = 3,
                            Pasillo = "B",
                            UltimoPago = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            Adeudo = 0m,
                            Dimensiones = "3x3",
                            IdCliente = 1,
                            Numero = 4,
                            Pasillo = "B",
                            UltimoPago = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("RentaContenedores.Models.Contenedor", b =>
                {
                    b.HasOne("RentaContenedores.Models.Cliente", "Cliente")
                        .WithMany("Contenedores")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("fk_contenedor_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("RentaContenedores.Models.Cliente", b =>
                {
                    b.Navigation("Contenedores");
                });
#pragma warning restore 612, 618
        }
    }
}
